2025-03-18 17:48:40,633 [INFO] USER:anand_yadav handlers.py:106:syndicate LOG: Configuration used: C:\Users\anand_yadav\AWS\task11\.syndicate-config-dev
2025-03-18 17:48:40,764 [WARNING] USER:anand_yadav __init__.py:190:initialize_project_state LOG: [93mConfig is set and generated but project state does not exist, seems that you've come from the previous version.[0m
2025-03-18 17:48:40,764 [WARNING] USER:anand_yadav __init__.py:193:initialize_project_state LOG: [93mGenerating project state file (.syndicate) from the existing structure...[0m
2025-03-18 17:48:40,767 [INFO] USER:anand_yadav project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\anand_yadav\AWS\task11\app\lambdas.
2025-03-18 17:48:40,769 [INFO] USER:anand_yadav project_state.py:400:_update_lambdas_from_path LOG: Going to add the following 'nodejs' lambda:'api_handler' to the pending ProjectState.
2025-03-18 17:48:40,770 [INFO] USER:anand_yadav processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-18 17:48:42,102 [INFO] USER:anand_yadav project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-18 17:48:42,102 [INFO] USER:anand_yadav project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-18 17:48:42,490 [INFO] USER:anand_yadav sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-18 17:48:43,857 [INFO] USER:anand_yadav handlers.py:142:test LOG: Running tests...
2025-03-18 17:48:43,858 [INFO] USER:anand_yadav handlers.py:150:test LOG: Tests not found, 'tests' folder is missing in 'C:/Users/anand_yadav/AWS/task11'.
2025-03-18 17:48:43,858 [INFO] USER:anand_yadav helper.py:330:timed LOG: Stage test, elapsed time: 0:00:00.000980
2025-03-18 17:48:43,864 [INFO] USER:anand_yadav handlers.py:993:assemble LOG: Building artifacts, bundle: task11_250318.174842
2025-03-18 17:48:43,864 [INFO] USER:anand_yadav project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\anand_yadav\AWS\task11\jsrc\main\java\com\task11.
2025-03-18 17:48:43,865 [INFO] USER:anand_yadav project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\anand_yadav\AWS\task11\src\lambdas.
2025-03-18 17:48:43,865 [INFO] USER:anand_yadav project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\anand_yadav\AWS\task11\app\lambdas.
2025-03-18 17:48:43,865 [INFO] USER:anand_yadav project_state.py:400:_update_lambdas_from_path LOG: Going to add the following 'nodejs' lambda:'api_handler' to the pending ProjectState.
2025-03-18 17:48:43,866 [INFO] USER:anand_yadav project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\anand_yadav\AWS\task11\dnapp\lambdas.
2025-03-18 17:48:43,866 [INFO] USER:anand_yadav project_state.py:430:_update_bpm_resources_from_path LOG: Going to resolve any build project mapping dependent resources from a given path: C:\Users\anand_yadav\AWS\task11\swagger_src.
2025-03-18 17:48:43,866 [INFO] USER:anand_yadav project_state.py:430:_update_bpm_resources_from_path LOG: Going to resolve any build project mapping dependent resources from a given path: C:\Users\anand_yadav\AWS\task11\appsync_src.
2025-03-18 17:48:43,870 [INFO] USER:anand_yadav handlers.py:821:assemble_node LOG: Command assemble node: project_path: app 
2025-03-18 17:48:43,870 [INFO] USER:anand_yadav nodejs.py:58:assemble_node_lambdas LOG: Going to package lambdas starting by path C:\Users\anand_yadav\AWS\task11\app
2025-03-18 17:48:43,871 [INFO] USER:anand_yadav nodejs.py:64:assemble_node_lambdas LOG: Going to build artifact in: C:\Users\anand_yadav\AWS\task11\app\lambdas\api_handler
2025-03-18 17:48:44,204 [INFO] USER:anand_yadav nodejs.py:123:install_requirements LOG: Artifacts path: C:\Users\anand_yadav\AWS\task11\.syndicate-config-dev\bundles\task11_250318.174842\api_handler-1.0
2025-03-18 17:48:49,879 [INFO] USER:anand_yadav helper.py:107:execute_command_by_path LOG: Running the command "npm install"

added 45 packages, and audited 46 packages in 5s

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm warn deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm notice
npm notice New major version of npm available! 10.9.2 -> 11.2.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.2.0
npm notice To update run: npm install -g npm@11.2.0
npm notice

2025-03-18 17:48:57,557 [INFO] USER:anand_yadav handlers.py:830:assemble_node LOG: NodeJS artifacts were prepared successfully.
2025-03-18 17:48:57,558 [INFO] USER:anand_yadav helper.py:330:timed LOG: Stage assemble_node, elapsed time: 0:00:13.687983
2025-03-18 17:48:57,562 [INFO] USER:anand_yadav helper.py:330:timed LOG: Stage assemble, elapsed time: 0:00:13.697624
2025-03-18 17:48:57,566 [INFO] USER:anand_yadav handlers.py:1037:package_meta LOG: Package meta, bundle: task11_250318.174842
2025-03-18 17:48:57,566 [INFO] USER:anand_yadav meta_processor.py:513:create_meta LOG: Bundle path: C:/Users/anand_yadav/AWS/task11/bundles/task11_250318.174842
2025-03-18 17:48:57,569 [INFO] USER:anand_yadav helper.py:292:write_content_to_file LOG: C:\Users\anand_yadav\AWS\task11\.syndicate-config-dev/bundles/task11_250318.174842\build_meta.json file was created.
2025-03-18 17:48:57,569 [INFO] USER:anand_yadav handlers.py:1040:package_meta LOG: Meta was configured successfully.
2025-03-18 17:48:57,570 [INFO] USER:anand_yadav helper.py:330:timed LOG: Stage package_meta, elapsed time: 0:00:00.003624
2025-03-18 17:48:58,618 [INFO] USER:anand_yadav handlers.py:1083:upload LOG: Upload bundle: task11_250318.174842
2025-03-18 17:48:59,727 [INFO] USER:anand_yadav bundle_processor.py:232:upload_bundle_to_s3 LOG: Bundle was validated successfully
2025-03-18 17:49:24,496 [INFO] USER:anand_yadav handlers.py:1090:upload LOG: Bundle was uploaded successfully
2025-03-18 17:49:24,497 [INFO] USER:anand_yadav helper.py:330:timed LOG: Stage upload, elapsed time: 0:00:26.920672
2025-03-18 17:49:24,506 [INFO] USER:anand_yadav helper.py:330:timed LOG: Stage build, elapsed time: 0:00:42.014571
2025-03-18 17:49:30,771 [INFO] USER:anand_yadav handlers.py:106:syndicate LOG: Configuration used: C:\Users\anand_yadav\AWS\task11\.syndicate-config-dev
2025-03-18 17:49:30,911 [INFO] USER:anand_yadav processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-18 17:49:32,131 [INFO] USER:anand_yadav project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-18 17:49:32,131 [INFO] USER:anand_yadav project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-18 17:49:32,513 [INFO] USER:anand_yadav sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-18 17:49:32,866 [INFO] USER:anand_yadav project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-18 17:49:32,866 [INFO] USER:anand_yadav project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-18 17:49:33,233 [INFO] USER:anand_yadav sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-18 17:49:33,234 [INFO] USER:anand_yadav helper.py:233:resolve_default_value LOG: Resolved value of deploy_name: task11
2025-03-18 17:49:33,619 [INFO] USER:anand_yadav project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-18 17:49:33,620 [INFO] USER:anand_yadav project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-18 17:49:33,986 [INFO] USER:anand_yadav sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-18 17:49:33,987 [INFO] USER:anand_yadav helper.py:233:resolve_default_value LOG: Resolved value of bundle_name: task11_250318.174842
2025-03-18 17:49:34,369 [INFO] USER:anand_yadav project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-18 17:49:34,369 [INFO] USER:anand_yadav project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-18 17:49:34,718 [INFO] USER:anand_yadav sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-18 17:49:35,077 [INFO] USER:anand_yadav project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-18 17:49:35,078 [INFO] USER:anand_yadav project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-18 17:49:35,444 [INFO] USER:anand_yadav sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-18 17:49:37,602 [INFO] USER:anand_yadav deployment_processor.py:451:create_deployment_resources LOG: The latest deployment has status failed. Loaded output:
 {
    "arn:aws:iam::890742610830:policy/cmtr-aafb0190-lambda-basic-execution": {
        "resource_name": "cmtr-aafb0190-lambda-basic-execution",
        "resource_meta": {
            "policy_content": {
                "Statement": [
                    {
                        "Action": [
                            "logs:CreateLogGroup",
                            "logs:CreateLogStream",
                            "logs:PutLogEvents",
                            "dynamodb:GetItem",
                            "dynamodb:Query",
                            "dynamodb:PutItem",
                            "dynamodb:Batch*",
                            "dynamodb:DeleteItem",
                            "ssm:PutParameter",
                            "ssm:GetParameter",
                            "kms:Decrypt",
                            "dynamodb:Scan",
                            "cognito-idp:DescribeUserPool",
                            "cognito-idp:GetUser",
                            "cognito-idp:ListUsers",
                            "cognito-idp:AdminCreateUser",
                            "cognito-idp:AdminInitiateAuth",
                            "cognito-idp:AdminSetUserPassword",
                            "cognito-idp:GetIdentityProviderByIdentifier",
                            "cognito-idp:ListUserPools",
                            "cognito-idp:ListUserPoolClients",
                            "cognito-idp:AdminRespondToAuthChallenge",
                            "cognito-idp:AdminConfirmSignUp"
                        ],
                        "Effect": "Allow",
                        "Resource": "*"
                    }
                ],
                "Version": "2012-10-17"
            },
            "resource_type": "iam_policy",
            "tags": {
                "run_id": "JAP-11",
                "run_type": "stm",
                "type": "user",
                "user_id": "aafb0190"
            },
            "processed": true
        },
        "description": {
            "PolicyName": "cmtr-aafb0190-lambda-basic-execution",
            "PolicyId": "ANPA46ZDFTOHOZ7OPRDHL",
            "Path": "/",
            "DefaultVersionId": "v1",
            "AttachmentCount": 5,
            "PermissionsBoundaryUsageCount": 0,
            "IsAttachable": true,
            "CreateDate": "2025-03-11T10:23:45+00:00",
            "UpdateDate": "2025-03-11T10:23:45+00:00",
            "Tags": [
                {
                    "Key": "run_id",
                    "Value": "JAP-11"
                },
                {
                    "Key": "run_type",
                    "Value": "stm"
                },
                {
                    "Key": "type",
                    "Value": "user"
                },
                {
                    "Key": "user_id",
                    "Value": "aafb0190"
                }
            ]
        }
    },
    "arn:aws:iam::890742610830:role/cmtr-aafb0190-api_handler-role": {
        "resource_name": "cmtr-aafb0190-api_handler-role",
        "resource_meta": {
            "predefined_policies": [],
            "principal_service": "lambda",
            "custom_policies": [
                "cmtr-aafb0190-lambda-basic-execution"
            ],
            "resource_type": "iam_role",
            "tags": {
                "run_id": "JAP-11",
                "run_type": "stm",
                "type": "user",
                "user_id": "aafb0190"
            },
            "processed": true
        },
        "description": {
            "Path": "/",
            "RoleName": "cmtr-aafb0190-api_handler-role",
            "RoleId": "AROA46ZDFTOHJF2U6ZPFF",
            "CreateDate": "2025-03-12T08:37:12+00:00",
            "AssumeRolePolicyDocument": {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Sid": "",
                        "Effect": "Allow",
                        "Principal": {
                            "AWS": "arn:aws:iam::890742610830:root"
                        },
                        "Action": "sts:AssumeRole"
                    },
                    {
                        "Effect": "Allow",
                        "Principal": {
                            "Service": "lambda.amazonaws.com"
                        },
                        "Action": "sts:AssumeRole"
                    }
                ]
            },
            "MaxSessionDuration": 3600,
            "Tags": [
                {
                    "Key": "run_id",
                    "Value": "JAP-11"
                },
                {
                    "Key": "run_type",
                    "Value": "stm"
                },
                {
                    "Key": "type",
                    "Value": "user"
                },
                {
                    "Key": "user_id",
                    "Value": "aafb0190"
                }
            ],
            "RoleLastUsed": {
                "LastUsedDate": "2025-03-13T09:10:36+00:00",
                "Region": "eu-west-1"
            }
        }
    }
}
2025-03-18 17:49:37,808 [INFO] USER:anand_yadav deployment_processor.py:466:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved
2025-03-18 17:49:37,809 [INFO] USER:anand_yadav deployment_processor.py:489:create_deployment_resources LOG: Going to deploy AWS resources
2025-03-18 17:49:37,809 [WARNING] USER:anand_yadav deployment_processor.py:275:deploy_resources LOG: Resource dependency with higher deployment priority from a resource with equal or lower deployment priority detected. Deployment may take a little bit more time than usual.
2025-03-18 17:49:37,978 [INFO] USER:anand_yadav deployment_processor.py:181:_process_resources_with_dependencies LOG: Processing iam_policy resources
2025-03-18 17:49:39,477 [WARNING] USER:anand_yadav iam_resource.py:115:_create_policy_from_meta LOG: IAM policy cmtr-aafb0190-lambda-basic-execution exists.
2025-03-18 17:49:39,782 [INFO] USER:anand_yadav deployment_processor.py:181:_process_resources_with_dependencies LOG: Processing iam_role resources
2025-03-18 17:49:40,078 [WARNING] USER:anand_yadav iam_resource.py:141:_create_role_from_meta LOG: IAM role cmtr-aafb0190-api_handler-role exists.
2025-03-18 17:49:40,078 [INFO] USER:anand_yadav deployment_processor.py:181:_process_resources_with_dependencies LOG: Processing dynamodb_table resources
2025-03-18 17:49:41,098 [ERROR] USER:anand_yadav deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-aafb0190-${tables_table}. An error occurred (ValidationException) when calling the DescribeTable operation: 1 validation error detected: Value 'cmtr-aafb0190-${tables_table}' at 'tableName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+
2025-03-18 17:49:41,291 [ERROR] USER:anand_yadav deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-aafb0190-${reservations_table}. An error occurred (ValidationException) when calling the DescribeTable operation: 1 validation error detected: Value 'cmtr-aafb0190-${reservations_table}' at 'tableName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+
2025-03-18 17:49:41,292 [INFO] USER:anand_yadav deployment_processor.py:159:_process_resources_with_dependencies LOG: Processing 'lambda' 'cmtr-aafb0190-api_handler' dependencies [
    {
        "resource_name": "cmtr-aafb0190-${booking_userpool}",
        "resource_type": "cognito_idp"
    }
]
2025-03-18 17:49:41,292 [INFO] USER:anand_yadav deployment_processor.py:181:_process_resources_with_dependencies LOG: Processing cognito_idp resources
2025-03-18 17:49:42,291 [WARNING] USER:anand_yadav cognito_identity_provider_connection.py:190:if_pool_exists_by_name LOG: Cognito User Pool with the name "cmtr-aafb0190-${booking_userpool}" not found in the region eu-west-1
2025-03-18 17:49:42,292 [INFO] USER:anand_yadav cognito_user_pool_resource.py:79:_create_cognito_user_pool_from_meta LOG: Creating user pool cmtr-aafb0190-${booking_userpool}
2025-03-18 17:49:42,526 [ERROR] USER:anand_yadav deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-aafb0190-${booking_userpool}. An error occurred (InvalidParameterException) when calling the CreateUserPool operation: 1 validation error detected: Value 'cmtr-aafb0190-${booking_userpool}' at 'poolName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w\s+=,.@-]+
2025-03-18 17:49:42,733 [WARNING] USER:anand_yadav cognito_identity_provider_connection.py:190:if_pool_exists_by_name LOG: Cognito User Pool with the name "cmtr-aafb0190-${booking_userpool}" not found in the region eu-west-1
2025-03-18 17:49:42,907 [WARNING] USER:anand_yadav bundle_processor.py:110:remove_failed_deploy_output LOG: Failed output file for deploy task11 does not exist
2025-03-18 17:49:42,907 [INFO] USER:anand_yadav deployment_processor.py:527:create_deployment_resources LOG: Going to apply post deployment tags
2025-03-18 17:49:42,916 [INFO] USER:anand_yadav group_tagging_api_resource.py:135:apply_tags LOG: Tags were successfully applied
2025-03-18 17:49:42,916 [INFO] USER:anand_yadav deployment_processor.py:530:create_deployment_resources LOG: Going to create deploy output
2025-03-18 17:49:43,470 [INFO] USER:anand_yadav bundle_processor.py:71:create_deploy_output LOG: Output file with name task11_250318.174842/outputs/task11_failed.json has been created
2025-03-18 17:49:43,470 [INFO] USER:anand_yadav deployment_processor.py:560:create_deployment_resources LOG: Deploy output for task11 was created.
2025-03-18 17:49:43,471 [WARNING] USER:anand_yadav handlers.py:344:deploy LOG: Backend resources were deployed with errors. See deploy output file.
2025-03-18 17:49:43,471 [INFO] USER:anand_yadav helper.py:330:timed LOG: Stage deploy, elapsed time: 0:00:08.026634
2025-03-18 17:49:43,857 [INFO] USER:anand_yadav project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-18 17:49:43,857 [INFO] USER:anand_yadav project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-18 17:49:44,209 [INFO] USER:anand_yadav sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-18 17:50:41,326 [INFO] USER:anand_yadav handlers.py:106:syndicate LOG: Configuration used: C:\Users\anand_yadav\AWS\task11\.syndicate-config-dev
2025-03-18 17:50:41,464 [INFO] USER:anand_yadav processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-18 17:50:42,635 [INFO] USER:anand_yadav project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-18 17:50:42,635 [INFO] USER:anand_yadav project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-18 17:50:43,002 [INFO] USER:anand_yadav sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-18 17:50:43,382 [INFO] USER:anand_yadav project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-18 17:50:43,382 [INFO] USER:anand_yadav project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-18 17:50:43,752 [INFO] USER:anand_yadav sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-18 17:50:43,752 [INFO] USER:anand_yadav helper.py:233:resolve_default_value LOG: Resolved value of deploy_name: task11
2025-03-18 17:50:44,096 [INFO] USER:anand_yadav project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-18 17:50:44,096 [INFO] USER:anand_yadav project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-18 17:50:44,468 [INFO] USER:anand_yadav sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-18 17:50:44,469 [INFO] USER:anand_yadav helper.py:233:resolve_default_value LOG: Resolved value of bundle_name: task11_250318.174842
2025-03-18 17:50:44,810 [INFO] USER:anand_yadav project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-18 17:50:44,810 [INFO] USER:anand_yadav project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-18 17:50:45,185 [INFO] USER:anand_yadav sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-18 17:50:45,602 [INFO] USER:anand_yadav project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-18 17:50:45,602 [INFO] USER:anand_yadav project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-18 17:50:45,970 [INFO] USER:anand_yadav sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-18 17:50:47,939 [INFO] USER:anand_yadav deployment_processor.py:451:create_deployment_resources LOG: The latest deployment has status failed. Loaded output:
 {
    "arn:aws:iam::890742610830:policy/cmtr-aafb0190-lambda-basic-execution": {
        "resource_name": "cmtr-aafb0190-lambda-basic-execution",
        "resource_meta": {
            "policy_content": {
                "Statement": [
                    {
                        "Action": [
                            "logs:CreateLogGroup",
                            "logs:CreateLogStream",
                            "logs:PutLogEvents",
                            "dynamodb:GetItem",
                            "dynamodb:Query",
                            "dynamodb:PutItem",
                            "dynamodb:Batch*",
                            "dynamodb:DeleteItem",
                            "ssm:PutParameter",
                            "ssm:GetParameter",
                            "kms:Decrypt",
                            "dynamodb:Scan",
                            "cognito-idp:DescribeUserPool",
                            "cognito-idp:GetUser",
                            "cognito-idp:ListUsers",
                            "cognito-idp:AdminCreateUser",
                            "cognito-idp:AdminInitiateAuth",
                            "cognito-idp:AdminSetUserPassword",
                            "cognito-idp:GetIdentityProviderByIdentifier",
                            "cognito-idp:ListUserPools",
                            "cognito-idp:ListUserPoolClients",
                            "cognito-idp:AdminRespondToAuthChallenge",
                            "cognito-idp:AdminConfirmSignUp"
                        ],
                        "Effect": "Allow",
                        "Resource": "*"
                    }
                ],
                "Version": "2012-10-17"
            },
            "resource_type": "iam_policy",
            "tags": {
                "run_id": "JAP-11",
                "run_type": "stm",
                "type": "user",
                "user_id": "aafb0190"
            },
            "processed": true
        },
        "description": {
            "PolicyName": "cmtr-aafb0190-lambda-basic-execution",
            "PolicyId": "ANPA46ZDFTOHOZ7OPRDHL",
            "Path": "/",
            "DefaultVersionId": "v1",
            "AttachmentCount": 6,
            "PermissionsBoundaryUsageCount": 0,
            "IsAttachable": true,
            "CreateDate": "2025-03-11T10:23:45+00:00",
            "UpdateDate": "2025-03-11T10:23:45+00:00",
            "Tags": [
                {
                    "Key": "run_id",
                    "Value": "JAP-11"
                },
                {
                    "Key": "run_type",
                    "Value": "stm"
                },
                {
                    "Key": "type",
                    "Value": "user"
                },
                {
                    "Key": "user_id",
                    "Value": "aafb0190"
                }
            ]
        }
    },
    "arn:aws:iam::890742610830:role/cmtr-aafb0190-api_handler-role": {
        "resource_name": "cmtr-aafb0190-api_handler-role",
        "resource_meta": {
            "predefined_policies": [],
            "principal_service": "lambda",
            "custom_policies": [
                "cmtr-aafb0190-lambda-basic-execution"
            ],
            "resource_type": "iam_role",
            "tags": {
                "run_id": "JAP-11",
                "run_type": "stm",
                "type": "user",
                "user_id": "aafb0190"
            },
            "processed": true
        },
        "description": {
            "Path": "/",
            "RoleName": "cmtr-aafb0190-api_handler-role",
            "RoleId": "AROA46ZDFTOHJF2U6ZPFF",
            "CreateDate": "2025-03-12T08:37:12+00:00",
            "AssumeRolePolicyDocument": {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Sid": "",
                        "Effect": "Allow",
                        "Principal": {
                            "AWS": "arn:aws:iam::890742610830:root"
                        },
                        "Action": "sts:AssumeRole"
                    },
                    {
                        "Effect": "Allow",
                        "Principal": {
                            "Service": "lambda.amazonaws.com"
                        },
                        "Action": "sts:AssumeRole"
                    }
                ]
            },
            "MaxSessionDuration": 3600,
            "Tags": [
                {
                    "Key": "run_id",
                    "Value": "JAP-11"
                },
                {
                    "Key": "run_type",
                    "Value": "stm"
                },
                {
                    "Key": "type",
                    "Value": "user"
                },
                {
                    "Key": "user_id",
                    "Value": "aafb0190"
                }
            ],
            "RoleLastUsed": {
                "LastUsedDate": "2025-03-13T09:10:36+00:00",
                "Region": "eu-west-1"
            }
        }
    }
}
2025-03-18 17:50:48,115 [INFO] USER:anand_yadav deployment_processor.py:466:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved
2025-03-18 17:50:48,116 [INFO] USER:anand_yadav deployment_processor.py:489:create_deployment_resources LOG: Going to deploy AWS resources
2025-03-18 17:50:48,116 [WARNING] USER:anand_yadav deployment_processor.py:275:deploy_resources LOG: Resource dependency with higher deployment priority from a resource with equal or lower deployment priority detected. Deployment may take a little bit more time than usual.
2025-03-18 17:50:48,255 [INFO] USER:anand_yadav deployment_processor.py:181:_process_resources_with_dependencies LOG: Processing iam_policy resources
2025-03-18 17:50:49,762 [WARNING] USER:anand_yadav iam_resource.py:115:_create_policy_from_meta LOG: IAM policy cmtr-aafb0190-lambda-basic-execution exists.
2025-03-18 17:50:50,101 [INFO] USER:anand_yadav deployment_processor.py:181:_process_resources_with_dependencies LOG: Processing iam_role resources
2025-03-18 17:50:50,416 [WARNING] USER:anand_yadav iam_resource.py:141:_create_role_from_meta LOG: IAM role cmtr-aafb0190-api_handler-role exists.
2025-03-18 17:50:50,416 [INFO] USER:anand_yadav deployment_processor.py:181:_process_resources_with_dependencies LOG: Processing dynamodb_table resources
2025-03-18 17:50:51,362 [ERROR] USER:anand_yadav deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-aafb0190-${tables_table}. An error occurred (ValidationException) when calling the DescribeTable operation: 1 validation error detected: Value 'cmtr-aafb0190-${tables_table}' at 'tableName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+
2025-03-18 17:50:51,539 [ERROR] USER:anand_yadav deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-aafb0190-${reservations_table}. An error occurred (ValidationException) when calling the DescribeTable operation: 1 validation error detected: Value 'cmtr-aafb0190-${reservations_table}' at 'tableName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+
2025-03-18 17:50:51,539 [INFO] USER:anand_yadav deployment_processor.py:159:_process_resources_with_dependencies LOG: Processing 'lambda' 'cmtr-aafb0190-api_handler' dependencies [
    {
        "resource_name": "cmtr-aafb0190-${booking_userpool}",
        "resource_type": "cognito_idp"
    }
]
2025-03-18 17:50:51,539 [INFO] USER:anand_yadav deployment_processor.py:181:_process_resources_with_dependencies LOG: Processing cognito_idp resources
2025-03-18 17:50:52,456 [WARNING] USER:anand_yadav cognito_identity_provider_connection.py:190:if_pool_exists_by_name LOG: Cognito User Pool with the name "cmtr-aafb0190-${booking_userpool}" not found in the region eu-west-1
2025-03-18 17:50:52,456 [INFO] USER:anand_yadav cognito_user_pool_resource.py:79:_create_cognito_user_pool_from_meta LOG: Creating user pool cmtr-aafb0190-${booking_userpool}
2025-03-18 17:50:52,679 [ERROR] USER:anand_yadav deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-aafb0190-${booking_userpool}. An error occurred (InvalidParameterException) when calling the CreateUserPool operation: 1 validation error detected: Value 'cmtr-aafb0190-${booking_userpool}' at 'poolName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w\s+=,.@-]+
2025-03-18 17:50:52,887 [WARNING] USER:anand_yadav cognito_identity_provider_connection.py:190:if_pool_exists_by_name LOG: Cognito User Pool with the name "cmtr-aafb0190-${booking_userpool}" not found in the region eu-west-1
2025-03-18 17:50:53,274 [INFO] USER:anand_yadav deployment_processor.py:527:create_deployment_resources LOG: Going to apply post deployment tags
2025-03-18 17:50:53,280 [INFO] USER:anand_yadav group_tagging_api_resource.py:135:apply_tags LOG: Tags were successfully applied
2025-03-18 17:50:53,280 [INFO] USER:anand_yadav deployment_processor.py:530:create_deployment_resources LOG: Going to create deploy output
2025-03-18 17:50:53,789 [INFO] USER:anand_yadav bundle_processor.py:71:create_deploy_output LOG: Output file with name task11_250318.174842/outputs/task11_failed.json has been created
2025-03-18 17:50:53,790 [INFO] USER:anand_yadav deployment_processor.py:560:create_deployment_resources LOG: Deploy output for task11 was created.
2025-03-18 17:50:53,790 [WARNING] USER:anand_yadav handlers.py:344:deploy LOG: Backend resources were deployed with errors. See deploy output file.
2025-03-18 17:50:53,791 [INFO] USER:anand_yadav helper.py:330:timed LOG: Stage deploy, elapsed time: 0:00:07.821050
2025-03-18 17:50:54,169 [INFO] USER:anand_yadav project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-18 17:50:54,169 [INFO] USER:anand_yadav project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-18 17:50:54,516 [INFO] USER:anand_yadav sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
